apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::260098403948:role/eksctl-eksctl-demo-nodegroup-ng-b-NodeInstanceRole-187GKPRKM2EXL
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::260098403948:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-14T17:50:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1970"
  uid: 721a7264-f985-4076-b242-af21f81dde07
